import {
  collection,
  doc,
  getDoc,
  getDocs,
  serverTimestamp,
  setDoc,
  updateDoc,
  type Firestore,
} from "firebase/firestore";
import {
  catalogIsAssignedToCustomer,
  catalogIsAssignedToJob,
  type JobProductSelectionDoc,
  type ProductCatalogDoc,
} from "@/lib/product-catalogs";
import {
  cloneQuestionnaireTemplateForJob,
  normalizeJobQuestionnaireTemplate,
  type JobQuestionnaireTemplate,
} from "@/lib/job-customer-questionnaire";

export const AUTO_CUSTOMER_TASK_SELECT_PRODUCTS = "auto_select_products";
export const AUTO_CUSTOMER_TASK_FILL_QUESTIONNAIRE = "auto_fill_questionnaire";

export type CustomerJobTaskType =
  | "select_products"
  | "fill_questionnaire"
  | "provide_details"
  | "confirm_info"
  | "upload_documents"
  | "custom";

export type CustomerJobTaskStatus = "pending" | "completed" | "cancelled";

export const CUSTOMER_JOB_TASK_TYPES: CustomerJobTaskType[] = [
  "select_products",
  "fill_questionnaire",
  "provide_details",
  "confirm_info",
  "upload_documents",
  "custom",
];

export const CUSTOMER_JOB_TASK_TYPE_LABELS: Record<CustomerJobTaskType, string> = {
  select_products: "Vybrat produkty",
  fill_questionnaire: "Vyplnit dotazník",
  provide_details: "Doplnit údaje",
  confirm_info: "Potvrdit informace",
  upload_documents: "Nahrát dokumenty",
  custom: "Vlastní úkol",
};

export interface CustomerJobTaskDoc {
  companyId: string;
  jobId: string;
  assignedCustomerUid: string;
  customerId?: string | null;
  title: string;
  description: string;
  type: CustomerJobTaskType;
  status: CustomerJobTaskStatus;
  dueDate?: string | null;
  autoGenerated: boolean;
  createdBy?: string | null;
  createdAt?: unknown;
  updatedAt?: unknown;
  completedAt?: unknown;
}

export async function getCustomerPortalUidForJob(
  firestore: Firestore,
  companyId: string,
  customerCrmId: string | null | undefined
): Promise<string | null> {
  const id = typeof customerCrmId === "string" ? customerCrmId.trim() : "";
  if (!id) return null;
  try {
    const ref = doc(firestore, "companies", companyId, "customers", id);
    const snap = await getDoc(ref);
    if (!snap.exists()) return null;
    const uid = (snap.data() as { customerPortalUid?: string }).customerPortalUid;
    return typeof uid === "string" && uid.trim() ? uid.trim() : null;
  } catch {
    return null;
  }
}

export function getAssignedProductCatalogsForJob(
  catalogs: Array<{ id: string } & Partial<ProductCatalogDoc>>,
  jobId: string,
  customerCrmId: string | null | undefined
): Array<{ id: string } & Partial<ProductCatalogDoc>> {
  return catalogs.filter(
    (c) =>
      c.active !== false &&
      c.customerVisible === true &&
      (catalogIsAssignedToJob(c, jobId) || catalogIsAssignedToCustomer(c, customerCrmId ?? undefined))
  );
}

export function isProductSelectionSatisfiedForUid(
  assignedCatalogs: Array<{ id: string } & Partial<ProductCatalogDoc>>,
  selections: Array<Partial<JobProductSelectionDoc> & { id?: string }>,
  portalUid: string
): boolean {
  if (assignedCatalogs.length === 0) return true;
  const byCatalog = new Map<string, JobProductSelectionDoc | Partial<JobProductSelectionDoc>>();
  for (const s of selections) {
    if (s.customerPortalUid !== portalUid || !s.catalogId) continue;
    byCatalog.set(s.catalogId, s);
  }
  for (const c of assignedCatalogs) {
    const sel = byCatalog.get(c.id);
    const ids = Array.isArray(sel?.selectedProductIds) ? sel.selectedProductIds : [];
    if (ids.length === 0) return false;
  }
  return true;
}

export function readJobQuestionnaireSnapshot(
  job: Record<string, unknown> | null | undefined
): JobQuestionnaireTemplate | null {
  if (!job) return null;
  const raw = job.customerQuestionnaireSnapshot;
  return normalizeJobQuestionnaireTemplate(raw);
}

export function questionnaireNeedsCompletion(
  q: JobQuestionnaireTemplate | null,
  responseStatus: string | null | undefined
): boolean {
  if (!q || q.active === false || !q.questions?.length) return false;
  return responseStatus !== "submitted";
}

function taskCollectionRef(firestore: Firestore, companyId: string, jobId: string) {
  return collection(firestore, "companies", companyId, "jobs", jobId, "customer_tasks");
}

function autoTaskPayload(
  companyId: string,
  jobId: string,
  assignedCustomerUid: string,
  customerId: string | null | undefined,
  kind: "select_products" | "fill_questionnaire",
  shouldPending: boolean,
  createdBy: string
): Record<string, unknown> {
  const isProducts = kind === "select_products";
  return {
    companyId,
    jobId,
    assignedCustomerUid,
    customerId: customerId ?? null,
    title: isProducts ? "Vyberte produkty" : "Vyplňte dotazník",
    description: isProducts
      ? "Vyberte produkty z katalogů přiřazených k této zakázce."
      : "Vyplňte prosím dotazník připravený firmou.",
    type: isProducts ? "select_products" : "fill_questionnaire",
    status: shouldPending ? "pending" : "completed",
    dueDate: null,
    autoGenerated: true,
    createdBy,
    updatedAt: serverTimestamp(),
    ...(shouldPending ? {} : { completedAt: serverTimestamp() }),
  };
}

/**
 * Synchronizuje automatické úkoly (produkty / dotazník). Volá administrátor z detailu zakázky.
 */
export async function syncAutoCustomerTasksForJob(
  firestore: Firestore,
  companyId: string,
  jobId: string,
  job: Record<string, unknown>,
  adminUid: string
): Promise<void> {
  const customerCrmId =
    typeof job.customerId === "string" && job.customerId.trim() ? job.customerId.trim() : null;
  const portalUid = await getCustomerPortalUidForJob(firestore, companyId, customerCrmId);
  if (!portalUid) return;

  const catalogsSnap = await getDocs(collection(firestore, "companies", companyId, "product_catalogs"));
  const catalogs = catalogsSnap.docs.map((d) => ({ id: d.id, ...d.data() })) as Array<
    { id: string } & Partial<ProductCatalogDoc>
  >;
  const assigned = getAssignedProductCatalogsForJob(catalogs, jobId, customerCrmId);

  const selSnap = await getDocs(
    collection(firestore, "companies", companyId, "jobs", jobId, "product_catalog_selections")
  );
  const selections = selSnap.docs.map((d) => ({ id: d.id, ...d.data() })) as Array<
    Partial<JobProductSelectionDoc> & { id?: string }
  >;

  const productsDone = isProductSelectionSatisfiedForUid(assigned, selections, portalUid);

  const qSnap = await getDoc(
    doc(
      firestore,
      "companies",
      companyId,
      "jobs",
      jobId,
      "customer_questionnaire_responses",
      portalUid
    )
  );
  const responseStatus = qSnap.exists()
    ? String((qSnap.data() as { status?: string }).status ?? "")
    : "";

  const qTpl = readJobQuestionnaireSnapshot(job);
  const questionnairePending = questionnaireNeedsCompletion(qTpl, responseStatus);

  const needProductsTask = assigned.length > 0 && !productsDone;
  const needQuestionnaireTask = questionnairePending;

  const productsRef = doc(taskCollectionRef(firestore, companyId, jobId), AUTO_CUSTOMER_TASK_SELECT_PRODUCTS);
  const questRef = doc(taskCollectionRef(firestore, companyId, jobId), AUTO_CUSTOMER_TASK_FILL_QUESTIONNAIRE);

  if (needProductsTask) {
    const existing = await getDoc(productsRef);
    const base = autoTaskPayload(
      companyId,
      jobId,
      portalUid,
      customerCrmId,
      "select_products",
      true,
      adminUid
    );
    await setDoc(
      productsRef,
      {
        ...base,
        createdAt: existing.exists() ? (existing.data() as { createdAt?: unknown }).createdAt : serverTimestamp(),
      },
      { merge: true }
    );
  } else {
    const existing = await getDoc(productsRef);
    if (existing.exists()) {
      const st = (existing.data() as { status?: string }).status;
      if (st === "pending") {
        await updateDoc(productsRef, {
          status: "completed",
          completedAt: serverTimestamp(),
          updatedAt: serverTimestamp(),
        });
      }
    }
  }

  if (needQuestionnaireTask) {
    const existing = await getDoc(questRef);
    const base = autoTaskPayload(
      companyId,
      jobId,
      portalUid,
      customerCrmId,
      "fill_questionnaire",
      true,
      adminUid
    );
    await setDoc(
      questRef,
      {
        ...base,
        createdAt: existing.exists() ? (existing.data() as { createdAt?: unknown }).createdAt : serverTimestamp(),
      },
      { merge: true }
    );
  } else {
    const existing = await getDoc(questRef);
    if (existing.exists()) {
      const st = (existing.data() as { status?: string }).status;
      if (st === "pending") {
        await updateDoc(questRef, {
          status: "completed",
          completedAt: serverTimestamp(),
          updatedAt: serverTimestamp(),
        });
      }
    }
  }
}

export async function completeCustomerTasksByTypes(
  firestore: Firestore,
  companyId: string,
  jobId: string,
  customerUid: string,
  types: CustomerJobTaskType[]
): Promise<void> {
  const uniq = new Set(types);
  const snap = await getDocs(taskCollectionRef(firestore, companyId, jobId));
  for (const d of snap.docs) {
    const data = d.data() as Partial<CustomerJobTaskDoc>;
    if (data.assignedCustomerUid !== customerUid) continue;
    if (!data.type || !uniq.has(data.type)) continue;
    if (data.status !== "pending") continue;
    await updateDoc(d.ref, {
      status: "completed",
      completedAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    });
  }
}

/** Dokončí známé automatické úkoly podle pevného ID dokumentu (rychlejší než procházet kolekci). */
export async function completeAutoCustomerTasksByKind(
  firestore: Firestore,
  companyId: string,
  jobId: string,
  customerUid: string,
  kinds: ("select_products" | "fill_questionnaire")[]
): Promise<void> {
  for (const k of kinds) {
    const id =
      k === "select_products"
        ? AUTO_CUSTOMER_TASK_SELECT_PRODUCTS
        : AUTO_CUSTOMER_TASK_FILL_QUESTIONNAIRE;
    const ref = doc(firestore, "companies", companyId, "jobs", jobId, "customer_tasks", id);
    const snap = await getDoc(ref);
    if (!snap.exists()) continue;
    const data = snap.data() as Partial<CustomerJobTaskDoc>;
    if (data.assignedCustomerUid !== customerUid || data.status !== "pending") continue;
    await updateDoc(ref, {
      status: "completed",
      completedAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    });
  }
}

export async function applyTemplateQuestionnaireToJobDocument(
  firestore: Firestore,
  companyId: string,
  jobId: string,
  templateQuestionnaire: unknown,
  templateId?: string | null
): Promise<boolean> {
  const normalized = normalizeJobQuestionnaireTemplate(templateQuestionnaire);
  if (!normalized) return false;
  const snapshot = cloneQuestionnaireTemplateForJob(normalized, templateId ?? undefined);
  const jobRef = doc(firestore, "companies", companyId, "jobs", jobId);
  await updateDoc(jobRef, {
    customerQuestionnaireSnapshot: snapshot,
    updatedAt: serverTimestamp(),
  });
  return true;
}
