import type { LucideIcon } from "lucide-react";
import {
  LayoutDashboard,
  Users,
  Briefcase,
  Inbox,
  Wallet,
  MessageSquare,
  FileText,
  Settings,
  CreditCard,
  UserCircle,
  Banknote,
  BarChart3,
  Tags,
  Activity,
  Package,
  Factory,
  Landmark,
  Receipt,
  CalendarClock,
  Mail,
  CircleHelp,
  Sparkles,
  ListChecks,
  CalendarDays,
  Timer,
  Stamp,
  UsersRound,
  FileStack,
} from "lucide-react";

/** Ikony položek portálu — sdílené sidebar + mobilní dlaždice. */
export const PORTAL_MENU_ICONS: Record<string, LucideIcon> = {
  overview: LayoutDashboard,
  employees: Users,
  labor: Wallet,
  customers: UserCircle,
  jobs: Briefcase,
  leads: Inbox,
  offers: Tags,
  productCatalogs: Package,
  customerChats: MessageSquare,
  emails: Mail,
  meetingRecords: CalendarClock,
  finance: Landmark,
  invoices: Receipt,
  documents: FileText,
  sklad: Package,
  vyroba: Factory,
  reports: BarChart3,
  activity: Activity,
  billing: CreditCard,
  vyuctovani: Banknote,
  chat: MessageSquare,
  help: CircleHelp,
  settings: Settings,
  aiCenter: Sparkles,
  /** Mobilní speciály (nejsou v sidebar defs). */
  calendar: CalendarDays,
  tasks: ListChecks,
  attendance: Timer,
  payroll: Wallet,
  hours: Timer,
  approvals: Stamp,
  costs: Landmark,
  team: UsersRound,
  docs: FileStack,
};

export function portalMenuIcon(id: string): LucideIcon {
  return PORTAL_MENU_ICONS[id] ?? LayoutDashboard;
}
