"use client";

import React, { useMemo, useState } from "react";
import Link from "next/link";
import { collection, doc, serverTimestamp, updateDoc } from "firebase/firestore";
import { useCollection, useFirestore, useMemoFirebase } from "@/firebase";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  CUSTOMER_JOB_TASK_TYPE_LABELS,
  type CustomerJobTaskType,
} from "@/lib/customer-job-tasks";
import { Loader2 } from "lucide-react";

type TaskRow = {
  id: string;
  title?: string;
  description?: string;
  type?: string;
  status?: string;
  dueDate?: string | null;
  autoGenerated?: boolean;
  assignedCustomerUid?: string;
};

type Props = {
  companyId: string;
  jobId: string;
  customerUid: string;
  jobName?: string;
};

function taskHref(jobId: string, type: string | undefined): string {
  if (type === "fill_questionnaire") return `/portal/customer/jobs/${jobId}#customer-questionnaire`;
  if (type === "select_products") return `/portal/customer/jobs/${jobId}#customer-product-catalogs`;
  return `/portal/customer/jobs/${jobId}`;
}

export function CustomerJobTasksSection({ companyId, jobId, customerUid, jobName }: Props) {
  const firestore = useFirestore();
  const [busyId, setBusyId] = useState<string | null>(null);

  const colRef = useMemoFirebase(
    () =>
      firestore && companyId && jobId
        ? collection(firestore, "companies", companyId, "jobs", jobId, "customer_tasks")
        : null,
    [firestore, companyId, jobId]
  );
  const { data: raw, isLoading } = useCollection(colRef);

  const tasks = useMemo(() => {
    const rows = (raw ?? []) as TaskRow[];
    return rows.filter(
      (t) => t.assignedCustomerUid === customerUid && (t.status ?? "pending") === "pending"
    );
  }, [raw, customerUid]);

  const markCompleted = async (taskId: string) => {
    if (!firestore || !companyId || !jobId) return;
    setBusyId(taskId);
    try {
      const ref = doc(firestore, "companies", companyId, "jobs", jobId, "customer_tasks", taskId);
      await updateDoc(ref, {
        status: "completed",
        completedAt: serverTimestamp(),
        updatedAt: serverTimestamp(),
      });
    } finally {
      setBusyId(null);
    }
  };

  if (isLoading) {
    return (
      <Card id="customer-tasks">
        <CardContent className="flex justify-center py-10">
          <Loader2 className="h-8 w-8 animate-spin text-primary" aria-label="Načítání úkolů" />
        </CardContent>
      </Card>
    );
  }

  if (tasks.length === 0) {
    return (
      <Card id="customer-tasks">
        <CardHeader>
          <CardTitle className="text-lg">Úkoly od administrátora</CardTitle>
          <CardDescription>
            Nemáte žádné aktivní úkoly{jobName ? ` u zakázky „${jobName}“. ` : ". "}
            Jakmile vám firma zadá úkol, zobrazí se zde.
          </CardDescription>
        </CardHeader>
      </Card>
    );
  }

  return (
    <Card id="customer-tasks" className="scroll-mt-4">
      <CardHeader>
        <CardTitle className="text-lg">Co je potřeba dokončit</CardTitle>
        <CardDescription>Úkoly zadané firmou u této zakázky.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-3">
        {tasks.map((t) => {
          const type = (t.type ?? "custom") as CustomerJobTaskType;
          const typeLabel = CUSTOMER_JOB_TASK_TYPE_LABELS[type] ?? type;
          return (
            <div
              key={t.id}
              className="flex flex-col gap-3 rounded-lg border border-slate-200 bg-slate-50/80 p-4 sm:flex-row sm:items-start sm:justify-between"
            >
              <div className="space-y-1 min-w-0">
                <div className="flex flex-wrap items-center gap-2">
                  <h3 className="font-semibold text-foreground leading-snug">{t.title ?? "Úkol"}</h3>
                  {t.autoGenerated ? (
                    <Badge variant="secondary" className="text-xs">
                      Automaticky
                    </Badge>
                  ) : null}
                </div>
                <p className="text-xs text-muted-foreground">{typeLabel}</p>
                {t.description ? (
                  <p className="text-sm text-slate-700 whitespace-pre-wrap">{t.description}</p>
                ) : null}
                {t.dueDate ? (
                  <p className="text-xs text-muted-foreground">Termín: {t.dueDate}</p>
                ) : null}
              </div>
              <div className="flex flex-wrap gap-2 shrink-0">
                <Button variant="outline" size="sm" asChild>
                  <Link href={taskHref(jobId, t.type)}>Otevřít</Link>
                </Button>
                <Button
                  size="sm"
                  disabled={busyId === t.id}
                  onClick={() => void markCompleted(t.id)}
                >
                  {busyId === t.id ? <Loader2 className="h-4 w-4 animate-spin" /> : "Označit splněno"}
                </Button>
              </div>
            </div>
          );
        })}
      </CardContent>
    </Card>
  );
}
