"use client";

import React, { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { collection, onSnapshot, type Firestore } from "firebase/firestore";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Loader2 } from "lucide-react";
import {
  CUSTOMER_JOB_TASK_TYPE_LABELS,
  type CustomerJobTaskType,
} from "@/lib/customer-job-tasks";

export type CustomerPortalTaskRow = {
  jobId: string;
  taskId: string;
  title: string;
  description: string;
  type: string;
  dueDate?: string | null;
  autoGenerated?: boolean;
};

type Props = {
  firestore: Firestore | null;
  companyId: string;
  customerUid: string;
  linkedJobIds: string[];
  jobNames?: Record<string, string>;
};

function taskHref(jobId: string, type: string): string {
  if (type === "fill_questionnaire") return `/portal/customer/jobs/${jobId}#customer-questionnaire`;
  if (type === "select_products") return `/portal/customer/jobs/${jobId}#customer-product-catalogs`;
  return `/portal/customer/jobs/${jobId}`;
}

export function CustomerPortalTasksHome({
  firestore,
  companyId,
  customerUid,
  linkedJobIds,
  jobNames = {},
}: Props) {
  const [rows, setRows] = useState<CustomerPortalTaskRow[]>([]);
  const [loading, setLoading] = useState(true);

  const key = useMemo(() => linkedJobIds.slice().sort().join(","), [linkedJobIds]);

  useEffect(() => {
    if (!firestore || !companyId || linkedJobIds.length === 0) {
      setRows([]);
      setLoading(false);
      return;
    }
    setLoading(true);
    const byJob: Record<string, Map<string, CustomerPortalTaskRow>> = {};
    const unsubs: Array<() => void> = [];

    const flush = () => {
      const out: CustomerPortalTaskRow[] = [];
      for (const m of Object.values(byJob)) {
        for (const r of m.values()) out.push(r);
      }
      out.sort((a, b) => (a.title || "").localeCompare(b.title || "", "cs"));
      setRows(out);
      setLoading(false);
    };

    for (const jobId of linkedJobIds) {
      byJob[jobId] = new Map();
      const col = collection(firestore, "companies", companyId, "jobs", jobId, "customer_tasks");
      const unsub = onSnapshot(
        col,
        (snap) => {
          const m = new Map<string, CustomerPortalTaskRow>();
          for (const d of snap.docs) {
            const t = d.data() as Record<string, unknown>;
            if (t.assignedCustomerUid !== customerUid) continue;
            if ((t.status as string | undefined) !== "pending") continue;
            m.set(d.id, {
              jobId,
              taskId: d.id,
              title: typeof t.title === "string" ? t.title : "Úkol",
              description: typeof t.description === "string" ? t.description : "",
              type: typeof t.type === "string" ? t.type : "custom",
              dueDate: typeof t.dueDate === "string" ? t.dueDate : null,
              autoGenerated: t.autoGenerated === true,
            });
          }
          byJob[jobId] = m;
          flush();
        },
        () => flush()
      );
      unsubs.push(unsub);
    }

    return () => {
      unsubs.forEach((u) => u());
    };
  }, [firestore, companyId, customerUid, key]);

  if (!companyId || linkedJobIds.length === 0) {
    return null;
  }

  if (loading) {
    return (
      <Card>
        <CardContent className="flex justify-center py-10">
          <Loader2 className="h-8 w-8 animate-spin text-primary" aria-label="Načítání úkolů" />
        </CardContent>
      </Card>
    );
  }

  if (rows.length === 0) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="text-lg">Úkoly od administrátora</CardTitle>
          <CardDescription>Nemáte žádné aktivní úkoly u přiřazených zakázek.</CardDescription>
        </CardHeader>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-lg">Úkoly od administrátora</CardTitle>
        <CardDescription>Přehled toho, co je potřeba u vašich zakázek dokončit.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-3">
        {rows.map((r) => {
          const jn = jobNames[r.jobId]?.trim() || `Zakázka ${r.jobId.slice(0, 6)}…`;
          const type = (r.type ?? "custom") as CustomerJobTaskType;
          const typeLabel = CUSTOMER_JOB_TASK_TYPE_LABELS[type] ?? r.type;
          return (
            <div
              key={`${r.jobId}_${r.taskId}`}
              className="rounded-lg border border-slate-200 bg-slate-50/80 p-4 space-y-2"
            >
              <div className="flex flex-wrap items-center gap-2">
                <span className="text-xs font-medium text-muted-foreground uppercase tracking-wide">
                  {jn}
                </span>
                {r.autoGenerated ? (
                  <Badge variant="secondary" className="text-xs">
                    Automaticky
                  </Badge>
                ) : null}
              </div>
              <h3 className="font-semibold leading-snug">{r.title}</h3>
              <p className="text-xs text-muted-foreground">{typeLabel}</p>
              {r.description ? (
                <p className="text-sm text-slate-700 whitespace-pre-wrap">{r.description}</p>
              ) : null}
              {r.dueDate ? (
                <p className="text-xs text-muted-foreground">Termín: {r.dueDate}</p>
              ) : null}
              <Button size="sm" variant="outline" asChild>
                <Link href={taskHref(r.jobId, r.type)}>Přejít k zakázce</Link>
              </Button>
            </div>
          );
        })}
      </CardContent>
    </Card>
  );
}
