"use client";

import React, { useCallback, useEffect, useMemo, useState } from "react";
import {
  addDoc,
  collection,
  doc,
  serverTimestamp,
  updateDoc,
} from "firebase/firestore";
import { useUser, useFirestore, useCollection, useMemoFirebase } from "@/firebase";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { useToast } from "@/hooks/use-toast";
import {
  applyTemplateQuestionnaireToJobDocument,
  CUSTOMER_JOB_TASK_TYPES,
  CUSTOMER_JOB_TASK_TYPE_LABELS,
  getCustomerPortalUidForJob,
  readJobQuestionnaireSnapshot,
  syncAutoCustomerTasksForJob,
  type CustomerJobTaskType,
} from "@/lib/customer-job-tasks";
import {
  cloneQuestionnaireTemplateForJob,
  normalizeJobQuestionnaireTemplate,
} from "@/lib/job-customer-questionnaire";
import type { JobTemplate } from "@/lib/job-templates";
import { NATIVE_SELECT_CLASS } from "@/lib/light-form-control-classes";
import { Loader2, RefreshCw, ClipboardList } from "lucide-react";

type Props = {
  companyId: string;
  jobId: string;
  job: Record<string, unknown>;
  canEdit: boolean;
};

type TaskDoc = {
  id: string;
  title?: string;
  description?: string;
  type?: string;
  status?: string;
  dueDate?: string | null;
  autoGenerated?: boolean;
  assignedCustomerUid?: string;
};

type ResponseDoc = {
  id: string;
  customerPortalUid?: string;
  status?: string;
  title?: string;
  submittedAt?: unknown;
  answers?: Record<string, unknown>;
};

export function JobCustomerTasksAdminSection({ companyId, jobId, job, canEdit }: Props) {
  const { user } = useUser();
  const firestore = useFirestore();
  const { toast } = useToast();
  const [syncing, setSyncing] = useState(false);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [savingTask, setSavingTask] = useState(false);
  const [applyTplId, setApplyTplId] = useState<string>("");
  const [applyBusy, setApplyBusy] = useState(false);
  const [form, setForm] = useState({
    title: "",
    description: "",
    type: "custom" as CustomerJobTaskType,
    dueDate: "",
  });

  const tasksRef = useMemoFirebase(
    () =>
      firestore && companyId && jobId
        ? collection(firestore, "companies", companyId, "jobs", jobId, "customer_tasks")
        : null,
    [firestore, companyId, jobId]
  );
  const { data: tasksRaw, isLoading: tasksLoading } = useCollection(tasksRef);

  const responsesRef = useMemoFirebase(
    () =>
      firestore && companyId && jobId
        ? collection(firestore, "companies", companyId, "jobs", jobId, "customer_questionnaire_responses")
        : null,
    [firestore, companyId, jobId]
  );
  const { data: responsesRaw, isLoading: respLoading } = useCollection(responsesRef);

  const templatesRef = useMemoFirebase(
    () =>
      firestore && companyId
        ? collection(firestore, "companies", companyId, "jobTemplates")
        : null,
    [firestore, companyId]
  );
  const { data: templatesRaw } = useCollection(templatesRef);

  const tasks = useMemo(() => (tasksRaw ?? []) as TaskDoc[], [tasksRaw]);
  const responses = useMemo(() => (responsesRaw ?? []) as ResponseDoc[], [responsesRaw]);
  const templatesList = useMemo(() => (templatesRaw ?? []) as Array<JobTemplate & { id?: string }>, [templatesRaw]);

  const jobQuestionnaire = useMemo(() => readJobQuestionnaireSnapshot(job), [job]);

  const runSync = useCallback(async () => {
    if (!firestore || !user?.uid) return;
    setSyncing(true);
    try {
      await syncAutoCustomerTasksForJob(firestore, companyId, jobId, job, user.uid);
      toast({ title: "Automatické úkoly aktualizovány" });
    } catch (e) {
      console.error(e);
      toast({ variant: "destructive", title: "Synchronizace se nezdařila" });
    } finally {
      setSyncing(false);
    }
  }, [firestore, user?.uid, companyId, jobId, job, toast]);

  useEffect(() => {
    if (!canEdit || !user?.uid || !firestore) return;
    void syncAutoCustomerTasksForJob(firestore, companyId, jobId, job, user.uid).catch(() => {});
  }, [canEdit, user?.uid, firestore, companyId, jobId, job]);

  const createManualTask = async () => {
    if (!firestore || !user?.uid || !form.title.trim()) {
      toast({ variant: "destructive", title: "Vyplňte název úkolu" });
      return;
    }
    const crmId =
      typeof job.customerId === "string" && job.customerId.trim() ? job.customerId.trim() : null;
    setSavingTask(true);
    try {
      const portalUid = await getCustomerPortalUidForJob(firestore, companyId, crmId);
      if (!portalUid) {
        toast({
          variant: "destructive",
          title: "Chybí propojený portál",
          description: "U zákazníka v CRM není nastavený účet klientského portálu.",
        });
        return;
      }
      await addDoc(collection(firestore, "companies", companyId, "jobs", jobId, "customer_tasks"), {
        companyId,
        jobId,
        assignedCustomerUid: portalUid,
        customerId: crmId,
        title: form.title.trim(),
        description: form.description.trim(),
        type: form.type,
        status: "pending",
        dueDate: form.dueDate.trim() || null,
        autoGenerated: false,
        createdBy: user.uid,
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp(),
      });
      toast({ title: "Úkol vytvořen" });
      setDialogOpen(false);
      setForm({ title: "", description: "", type: "custom", dueDate: "" });
    } catch (e) {
      console.error(e);
      toast({ variant: "destructive", title: "Úkol se nepodařilo uložit" });
    } finally {
      setSavingTask(false);
    }
  };

  const setTaskStatus = async (taskId: string, status: "pending" | "completed" | "cancelled") => {
    if (!firestore) return;
    try {
      const ref = doc(firestore, "companies", companyId, "jobs", jobId, "customer_tasks", taskId);
      await updateDoc(ref, {
        status,
        updatedAt: serverTimestamp(),
        ...(status === "completed" ? { completedAt: serverTimestamp() } : {}),
      });
      toast({ title: "Stav úkolu uložen" });
    } catch {
      toast({ variant: "destructive", title: "Změna stavu se nezdařila" });
    }
  };

  const applyQuestionnaireFromTemplate = async () => {
    if (!firestore || !applyTplId) {
      toast({ variant: "destructive", title: "Vyberte šablonu" });
      return;
    }
    const tpl = templatesList.find((t) => t.id === applyTplId);
    const q = normalizeJobQuestionnaireTemplate(tpl?.questionnaire);
    if (!q || !q.questions.length) {
      toast({
        variant: "destructive",
        title: "Šablona nemá dotazník",
        description: "V této šabloně nejsou definované žádné otázky.",
      });
      return;
    }
    setApplyBusy(true);
    try {
      const ok = await applyTemplateQuestionnaireToJobDocument(
        firestore,
        companyId,
        jobId,
        tpl?.questionnaire,
        applyTplId
      );
      if (ok) {
        toast({ title: "Dotazník z šablony byl přiřazen k zakázce" });
        if (user?.uid) {
          const snapshot = cloneQuestionnaireTemplateForJob(q, applyTplId);
          await syncAutoCustomerTasksForJob(
            firestore,
            companyId,
            jobId,
            { ...job, customerQuestionnaireSnapshot: snapshot },
            user.uid
          );
        }
      }
    } catch (e) {
      console.error(e);
      toast({ variant: "destructive", title: "Přiřazení dotazníku se nezdařilo" });
    } finally {
      setApplyBusy(false);
    }
  };

  if (!canEdit) {
    return null;
  }

  return (
    <Card>
      <CardHeader className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <CardTitle className="text-lg flex items-center gap-2">
            <ClipboardList className="h-5 w-5" />
            Úkoly zákazníka a dotazník
          </CardTitle>
          <CardDescription>
            Úkoly v portálu, automatické připomínky a odpovědi na dotazník u této zakázky.
          </CardDescription>
        </div>
        <Button
          type="button"
          variant="outline"
          size="sm"
          className="gap-2 shrink-0"
          disabled={syncing}
          onClick={() => void runSync()}
        >
          {syncing ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}
          Aktualizovat auto úkoly
        </Button>
      </CardHeader>
      <CardContent className="space-y-8">
        <div className="space-y-3">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <h3 className="text-sm font-semibold">Úkoly pro zákazníka</h3>
            <Button type="button" size="sm" onClick={() => setDialogOpen(true)}>
              Nový úkol
            </Button>
          </div>
          {tasksLoading ? (
            <div className="flex justify-center py-6">
              <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
            </div>
          ) : tasks.length === 0 ? (
            <p className="text-sm text-muted-foreground border border-dashed rounded-lg p-4 text-center">
              Zatím žádné úkoly. Vytvořte ruční úkol nebo použijte synchronizaci automatických úkolů.
            </p>
          ) : (
            <ul className="space-y-2">
              {tasks.map((t) => (
                <li
                  key={t.id}
                  className="flex flex-col gap-2 rounded-lg border bg-muted/20 p-3 sm:flex-row sm:items-center sm:justify-between"
                >
                  <div className="min-w-0 space-y-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="font-medium">{t.title ?? "—"}</span>
                      <Badge variant="outline">{t.status ?? "—"}</Badge>
                      {t.autoGenerated ? <Badge variant="secondary">Auto</Badge> : null}
                    </div>
                    <p className="text-xs text-muted-foreground">
                      {CUSTOMER_JOB_TASK_TYPE_LABELS[(t.type as CustomerJobTaskType) ?? "custom"] ??
                        t.type}
                    </p>
                    {t.description ? (
                      <p className="text-sm text-slate-700 whitespace-pre-wrap">{t.description}</p>
                    ) : null}
                  </div>
                  <div className="flex flex-wrap gap-2 shrink-0">
                    {t.status === "pending" ? (
                      <>
                        <Button
                          type="button"
                          variant="outline"
                          size="sm"
                          onClick={() => void setTaskStatus(t.id, "completed")}
                        >
                          Splněno
                        </Button>
                        <Button
                          type="button"
                          variant="ghost"
                          size="sm"
                          onClick={() => void setTaskStatus(t.id, "cancelled")}
                        >
                          Zrušit
                        </Button>
                      </>
                    ) : t.status === "cancelled" || t.status === "completed" ? (
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={() => void setTaskStatus(t.id, "pending")}
                      >
                        Znovu otevřít
                      </Button>
                    ) : null}
                  </div>
                </li>
              ))}
            </ul>
          )}
        </div>

        <div className="space-y-3 border-t pt-6">
          <h3 className="text-sm font-semibold">Dotazník na zakázce</h3>
          {jobQuestionnaire && jobQuestionnaire.active !== false && jobQuestionnaire.questions.length > 0 ? (
            <p className="text-sm text-muted-foreground">
              Aktivní dotazník „{jobQuestionnaire.title}“ — {jobQuestionnaire.questions.length} otázek (kopie
              na zakázce).
            </p>
          ) : (
            <p className="text-sm text-muted-foreground">
              Na zakázce zatím není přiřazený dotazník pro zákazníka.
            </p>
          )}
          {templatesList.length > 0 ? (
            <div className="flex flex-col gap-2 sm:flex-row sm:items-end">
              <div className="space-y-1 flex-1">
                <Label>Přiřadit dotazník ze šablony</Label>
                <select
                  className={NATIVE_SELECT_CLASS}
                  value={applyTplId}
                  onChange={(e) => setApplyTplId(e.target.value)}
                >
                  <option value="">— vyberte šablonu —</option>
                  {templatesList
                    .filter((t) => t.id)
                    .map((t) => (
                      <option key={t.id} value={t.id}>
                        {t.name ?? t.id}
                      </option>
                    ))}
                </select>
              </div>
              <Button
                type="button"
                disabled={applyBusy || !applyTplId}
                onClick={() => void applyQuestionnaireFromTemplate()}
              >
                {applyBusy ? <Loader2 className="h-4 w-4 animate-spin" /> : "Použít dotazník ze šablony"}
              </Button>
            </div>
          ) : null}
        </div>

        <div className="space-y-3 border-t pt-6">
          <h3 className="text-sm font-semibold">Odpovědi zákazníka (dotazník)</h3>
          {respLoading ? (
            <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
          ) : responses.length === 0 ? (
            <p className="text-sm text-muted-foreground">Zatím žádné uložené odpovědi.</p>
          ) : (
            <ul className="space-y-3">
              {responses.map((r) => (
                <li key={r.id} className="rounded-lg border p-3 text-sm space-y-1">
                  <div className="flex flex-wrap gap-2 items-center">
                    <Badge variant="outline">{r.status ?? "—"}</Badge>
                    <span className="text-xs text-muted-foreground font-mono">{r.customerPortalUid ?? r.id}</span>
                  </div>
                  {r.title ? <p className="font-medium">{r.title}</p> : null}
                  <pre className="text-xs bg-muted/40 rounded p-2 overflow-x-auto max-h-40 overflow-y-auto">
                    {JSON.stringify(r.answers ?? {}, null, 2)}
                  </pre>
                </li>
              ))}
            </ul>
          )}
        </div>
      </CardContent>

      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="bg-white border-slate-200 text-slate-900 max-w-lg" data-portal-dialog>
          <DialogHeader>
            <DialogTitle>Nový úkol pro zákazníka</DialogTitle>
          </DialogHeader>
          <div className="space-y-3 py-2">
            <div className="space-y-1">
              <Label>Název</Label>
              <Input
                value={form.title}
                onChange={(e) => setForm((p) => ({ ...p, title: e.target.value }))}
                placeholder="Např. Doplňte číslo popisné"
              />
            </div>
            <div className="space-y-1">
              <Label>Popis</Label>
              <Textarea
                value={form.description}
                onChange={(e) => setForm((p) => ({ ...p, description: e.target.value }))}
                placeholder="Podrobnosti pro zákazníka"
                className="min-h-[88px]"
              />
            </div>
            <div className="space-y-1">
              <Label>Typ úkolu</Label>
              <select
                className={NATIVE_SELECT_CLASS}
                value={form.type}
                onChange={(e) =>
                  setForm((p) => ({ ...p, type: e.target.value as CustomerJobTaskType }))
                }
              >
                {CUSTOMER_JOB_TASK_TYPES.map((t) => (
                  <option key={t} value={t}>
                    {CUSTOMER_JOB_TASK_TYPE_LABELS[t]}
                  </option>
                ))}
              </select>
            </div>
            <div className="space-y-1">
              <Label>Termín (volitelné, text)</Label>
              <Input
                value={form.dueDate}
                onChange={(e) => setForm((p) => ({ ...p, dueDate: e.target.value }))}
                placeholder="Např. 2026-04-15"
              />
            </div>
          </div>
          <DialogFooter>
            <Button type="button" variant="outline" onClick={() => setDialogOpen(false)}>
              Zrušit
            </Button>
            <Button type="button" disabled={savingTask} onClick={() => void createManualTask()}>
              {savingTask ? <Loader2 className="h-4 w-4 animate-spin" /> : "Vytvořit"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </Card>
  );
}
