/** Bezpečné logování fází e-mail integrace — nikdy nelogovat hesla. */
export type EmailLogPhase =
  | "EMAIL_CONNECT_START"
  | "EMAIL_IMAP_CONNECTED"
  | "EMAIL_SMTP_CONNECTED"
  | "EMAIL_SYNC_START"
  | "EMAIL_ACCOUNT_ID"
  | "EMAIL_MAILBOX_OPENED"
  | "EMAIL_UIDVALIDITY"
  | "EMAIL_UID_NEXT"
  | "EMAIL_LAST_SYNCED_UID"
  | "EMAIL_NEW_UID_RANGE"
  | "EMAIL_NEW_UIDS_COUNT"
  | "EMAIL_MESSAGES_FETCHED"
  | "EMAIL_MESSAGES_SAVED"
  | "EMAIL_SYNC_MESSAGES_FOUND"
  | "EMAIL_MESSAGES_FOUND"
  | "EMAIL_SYNC_COMPLETED"
  | "EMAIL_SYNC_COMPLETE"
  | "EMAIL_SYNC_PARTIAL"
  | "EMAIL_SYNC_BATCH_START"
  | "EMAIL_SYNC_BATCH_SIZE"
  | "EMAIL_SYNC_MESSAGE_SAVED"
  | "EMAIL_SYNC_ATTACHMENT_STORED"
  | "EMAIL_SYNC_BATCH_DONE"
  | "EMAIL_SYNC_PROGRESS"
  | "EMAIL_AUTH_ERROR"
  | "EMAIL_SYNC_ERROR"
  | "EMAIL_CONNECT_ERROR"
  | "EMAIL_ACCOUNT_FOUND"
  | "EMAIL_CREDENTIAL_FOUND"
  | "EMAIL_CREDENTIAL_DECRYPT_OK"
  | "EMAIL_IMAP_CONNECT_START"
  | "EMAIL_ENCRYPTION_KEY_MISSING"
  | "EMAIL_CREDENTIAL_MISSING"
  | "EMAIL_CREDENTIAL_DECRYPT_FAILED"
  | "EMAIL_IMAP_AUTH_FAILED"
  | "EMAIL_IMAP_CONNECTION_FAILED";

export function logEmailPhase(
  phase: EmailLogPhase,
  meta?: Record<string, string | number | boolean | null | undefined>
): void {
  const safe = meta ? JSON.stringify(meta) : "";
  console.log(`[email-mailbox] ${phase}${safe ? ` ${safe}` : ""}`);
}
